namespace Infrastructure.Persistence.DbContexts.Insurance.InsuranceSeed
{
    public static class Stammdaten
    {
        public static string[] GetLänder()
        {
            return new[]
            {
                "Afghanistan", "Ägypten", "Åland", "Albanien", "Algerien", "Amerikanische Jungferninseln",
                "Amerikanisch-Samoa", "Andorra", "Angola", "Anguilla", "Antarktika", "Antigua und Barbuda",
                "Äquatorialguinea", "Argentinien", "Armenien", "Aruba", "Aserbaidschan", "Äthiopien", "Australien",
                "Bahamas", "Bahrain", "Bangladesch", "Barbados", "Bassas da India", "Belarus", "Belgien", "Belize",
                "Benin", "Bermuda", "Bhutan", "Bolivien", "Bosnien und Herzegowina", "Botsuana", "Bouvetinsel",
                "Brasilien", "Britische Jungferninseln", "Britisches Territorium im Indischen Ozean",
                "Brunei Darussalam", "Bulgarien", "Burkina Faso", "Burundi", "Cabo Verde", "Chile", "China",
                "Clipperton", "Cookinseln", "Costa Rica", "Côte d'Ivoire", "Dänemark", "Deutschland", "Dominica",
                "Dominikanische Republik", "Dschibuti", "Ecuador", "El Salvador", "Eritrea", "Estland", "Eswatini",
                "Europa", "Falklandinseln", "Färöer", "Fidschi", "Finnland", "Frankreich",
                "Frankreich (metropolitanes)", "Französische Süd- und Antarktisgebiete", "Französisch-Guayana",
                "Französisch-Polynesien", "Gabun", "Gambia", "Gazastreifen", "Georgien", "Ghana", "Gibraltar",
                "Glorieuses", "Grenada", "Griechenland", "Grönland", "Großbritannien", "Guadeloupe", "Guam",
                "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard und McDonaldinseln",
                "Honduras", "Hongkong", "Indien", "Indonesien", "Insel Man", "Irak", "Iran", "Irland", "Island",
                "Israel", "Italien", "Jamaika", "Japan", "Jemen", "Jersey", "Jordanien", "Juan de Nova", "Kaimaninseln",
                "Kambodscha", "Kamerun", "Kanada", "Kasachstan", "Katar", "Kenia", "Kirgisistan", "Kiribati",
                "Kleinere Amerikanische Überseeinseln", "Kokosinseln (Keelinginseln)", "Kolumbien", "Komoren", "Kongo",
                "Kongo, Demokratische Republik", "Korea, Demokratische Volksrepublik", "Korea, Republik", "Kroatien",
                "Kuba", "Kuwait", "Laos", "Lesotho", "Lettland", "Libanon", "Liberia", "Libyen", "Liechtenstein",
                "Litauen", "Luxemburg", "Macau", "Madagaskar", "Malawi", "Malaysia", "Malediven", "Mali", "Malta",
                "Marokko", "Marshallinseln", "Martinique", "Mauretanien", "Mauritius", "Mayotte", "Mexiko",
                "Mikronesien", "Moldau", "Monaco", "Mongolei", "Montenegro", "Montserrat", "Mosambik", "Myanmar",
                "Namibia", "Nauru", "Nepal", "Neukaledonien", "Neuseeland", "Nicaragua", "Niederlande",
                "Niederländische Antillen", "Niger", "Nigeria", "Niue", "Nördliche Marianen", "Nordmazedonien",
                "Norfolkinsel", "Norwegen", "Oman", "Österreich", "Pakistan", "Palau", "Panama", "Papua-Neuguinea",
                "Paraguay", "Peru", "Philippinen", "Pitcairninseln", "Polen", "Portugal", "Puerto Rico", "Réunion",
                "Ruanda", "Rumänien", "Russische Föderation", "Saint-Martin", "Salomonen", "Sambia", "Samoa",
                "San Marino", "São Tomé und Príncipe", "Saudi-Arabien", "Schweden", "Schweiz", "Senegal", "Serbien",
                "Serbien und Montenegro", "Seychellen", "Sierra Leone", "Simbabwe", "Singapur", "Slowakei", "Slowenien",
                "Somalia", "Spanien", "Spitzbergen", "Sri Lanka", "St. Barthélemy",
                "St. Helena, Ascension und Tristan da Cunha", "St. Kitts und Nevis", "St. Lucia",
                "St. Pierre und Miquelon", "St. Vincent und die Grenadinen", "Südafrika", "Sudan",
                "Südgeorgien und die Südlichen Sandwichinseln", "Südsudan", "Suriname", "Syrien", "Tadschikistan",
                "Taiwan", "Tansania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad und Tobago",
                "Tromelin", "Tschad", "Tschechische Republik", "Tunesien", "Türkei", "Turkmenistan",
                "Turks- und Caicosinseln", "Tuvalu", "Uganda", "Ukraine", "Ungarn", "Uruguay", "Usbekistan", "Vanuatu",
                "Vatikanstadt", "Venezuela", "Vereinigte Arabische Emirate", "Vereinigte Staaten", "Vietnam",
                "Wallis und Futuna", "Weihnachtsinsel", "Westjordanland", "Westsahara", "Zentralafrikanische Republik",
                "Zypern"
            };
        }

        public static string[] GetBerufe()
        {
            return new[]
            {
                "Mechatroniker/-in", "Bauwerksmechaniker/in für Abbruch und Betontrenntechnik",
                "Assistent/in für Geovisualisierung", "Metallbauer/in", "Pharmakant/in",
                "Lebensmitteltechnische/r Assistent/in", "Stuckateur/in", "Luftverkehrskaufmann/-frau",
                "Fachkraft für Agrarservice", "Fleischer/in", "Raumausstatter/in", "Duales Studium Handel",
                "Geomatiker/in", "Technische/r Assistent/in für Mechatronik", "Berufsfeuerwehrmann/-frau",
                "Duales Studium Informatik", "Pilot/-in", "Schornsteinfeger/in", "Zerspanungsmechaniker/in",
                "Veranstaltungskaufmann/-frau", "Kriminalkommissar/in – Gehobener Kriminaldienst des Bundes",
                "Bäcker/in", "Klempner/in", "Brauer/in und Mälzer/in", "Süßwarentechnologe/-technologin",
                "Verfahrensmechaniker/in in der Hütten- und Halbzeugindustrie", "Physiklaborant/in",
                "Medientechnologe/-technologin Druck", "Technische/r Betriebswirt/in - Handwerk",
                "Papiertechnologe/-technologin", "Medientechnologe/-in Siebdruck", "Grafikdesigner/in", "Kanalbauer/in",
                "Kraftfahrzeugmechatroniker/in", "Hebamme/Entbindungspfleger", "Umweltschutztechnische/r Assistent/in",
                "IT-System-Kaufmann/-frau", "Baustoffprüfer/in", "Biologielaborant/in", "Schiffsmechaniker/-in",
                "Elektroniker/in für Automatisierungstechnik", "Spielzeughersteller/in",
                "Fachberater/in für Softwaretechniken",
                "Technische/r Assistent/in für naturkundliche Museen und Forschungsinstitute",
                "Bauten- und Objektbeschichter/in", "Packmitteltechnologe/-technologin",
                "Land- und Baumaschinenmechatroniker/in", "Duales Studium Maschinenbau",
                "Verfahrensmechaniker/in für Kunststoff- und Kautschuktechnik", "Chirurgiemechaniker/-in", "Gärtner/in",
                "Fremdsprachenkorrespondent/-in", "Edelsteinschleifer/in",
                "Fachangestellte/r für Medien- und Informationsdienste", "Technische/r Modellbauer/in",
                "Duales Studium Pflege", "Sport- und Fitnesskaufmann/-frau", "Elektroniker/-in Betriebstechnik",
                "Bergbautechnologe/-in", "Forstwirt/in", "Zimmerer/in", "Kaufmann/-frau im E-Commerce",
                "Fachkraft für Rohr-, Kanal- und Industrieservice", "Fachinformatiker/in", "Vermessungstechniker/in",
                "Maßschneider/in", "Friseur/in", "Duales Studium Sozialpädagogik", "Restaurantfachmann/-frau",
                "Berufskraftfahrer/in", "Erzieher/in für Jugend- und Heimerziehung",
                "Wirtschaftsassistent/in im Bereich Fremdsprachen", "Orthopädietechnik-Mechaniker/in",
                "Konstruktionsmechaniker/in", "Bankkaufmann/-frau", "Hotelfachmann/-frau",
                "Personaldienstleistungskaufmann/-frau", "Werkstoffprüfer/in", "Fliesen-, Platten- und Mosaikleger/in",
                "Medientechnologe/-technologin Druckverarbeitung", "Winzer/in", "Betriebswirt/in für Verkehr/Logistik",
                "Fachverkäufer/in im Lebensmittelhandwerk", "Kaufmann/-frau im Groß- und Außenhandel",
                "Fluggerätelektroniker/in", "Mechatroniker/in für Kältetechnik", "Ausbaufacharbeiter/in",
                "Verkäufer/in", "Hochbaufacharbeiter/in", "Elektroniker/in",
                "Sozialpädagogische/r Assistent/in / Kinderpfleger/in", "Duales Studium Fahrzeugtechnik",
                "Gießereimechaniker/in", "Maschinen- und Anlagenführer/in", "Gebäudereiniger/in",
                "Elektroniker/-in für Informations- und Systemtechnik", "Steinmetz/in und Steinbildhauer/in",
                "Verfahrensmechaniker/in für Brillenoptik", "Fahrzeuglackierer/in",
                "Verfahrensmechaniker/-in in der Steine- und Erdenindustrie",
                "Gehobener Auswärtiger Dienst - Diplom Verwaltungsfachwirt/in", "Duales Studium Elektrotechnik",
                "Biologisch-technische/r Assistent/in", "Gesundheits- und Krankenpflegehelfer/in", "Konditor/in",
                "Sportfachmann/-frau", "Industriekaufmann/-frau",
                "Anlagenmechaniker/in für Sanitär-, Heizungs- und Klimatechnik", "Duales Studium Medien", "Fotograf/in",
                "Elektroniker/-in für Gebäude- und Infrastruktursysteme", "Duales Studium BWL", "Handelsfachwirt/in",
                "Duales Studium Bauingenieurwesen", "Diplom-Rechtspfleger/in", "Kaufmann/-frau im Einzelhandel",
                "Justizfachangestellte/r", "Fremdsprachensekretär/in", "Wirtschaftsassistent/in im Bereich Medien",
                "Assistent/in für Produktdesign", "Lokführer/in / Eisenbahner/in im Betriebsdienst",
                "Lasertechnische/r Assistent/in", "Rechtsanwaltsfachangestellte/r",
                "Fachberater/in für integrierte Systeme", "Duales Studium Wirtschaftsinformatik",
                "Informations- und Telekommunikationssystem-Elektroniker/in",
                "Duales Studium Zoll (gehobener nichttechnischer Dienst)", "Zweiradmechatroniker/in",
                "Medienassistent/-in", "Technische/r Assistent/in für nachwachsende Rohstoffe",
                "Zahnmedizinische/r Fachangestellte/r", "Betriebswirt/in im Außenhandel", "Fachkraft für Lagerlogistik",
                "Dolmetscher/in", "Tiermedizinische/r Fachangestellte/r", "Technische/r Systeminformatiker/in",
                "Betriebsassistent/in im Handwerk", "Immobilienkaufmann/-frau", "Fachwirt/in Vertrieb im Einzelhandel",
                "Industrietechnologe/-technologin", "Milchwirtschaftliche/r Laborant/in", "Triebfahrzeugführer/-in",
                "Duales Studium Polizei", "Außenhandelsassistent/in", "Elektrotechnische/r Offiziersassistent/in",
                "Fachangestellter für Markt- und Sozialforschung", "Notfallsanitäter/in", "Finanzwirt/in",
                "Fachkraft für Möbel-, Küchen- und Umzugsservice", "Fachkraft für Fruchtsafttechnik",
                "Oberflächenbeschichter/in", "Verfahrensmechaniker/in Glastechnik", "Sportassistent/in",
                "Heilerziehungspfleger/in", "Logopäde/Logopädin", "Feinwerkmechaniker/in", "Tierpfleger/in",
                "Werkzeugmechaniker/in", "Fertigungsmechaniker/in", "Automobilkaufmann/-frau",
                "Betriebswirt/in für Textil", "Technische/r Produktdesigner/in",
                "Fachkraft für Kurier-, Express- und Postdienstleistungen",
                "Duales Studium Bundesnachrichtendienst (gehobener nichttechnischer Dienst)", "Tischler/in",
                "Duales Studium Mediendesign", "Fachkraft für Abwassertechnik",
                "Kaufmann/-frau für Versicherungen und Finanzen", "Elektroniker/in für Maschinen und Antriebstechnik",
                "Steuerfachangestellte/r", "Fotomedienfachmann/-frau", "Heilerziehungspflegehelfer/-in",
                "Kommunikationsdesigner/in", "Mathematisch-technische/r Softwareentwickler/in",
                "Informationselektroniker/in", "Produktionsmechaniker/in – Textil", "Dachdecker/in",
                "Duales Studium Wirtschaft und Management", "Physikalisch-technische/r Assistent/in",
                "Systemelektroniker/in", "Hörakustiker/in", "Duales Studium Logistik", "Mikrotechnologe/-technologin",
                "Management-/Direktionsassistent/in", "Touristikassistent/in",
                "Kaufmann/-frau für Spedition und Logistikdienstleistung", "Fachangestellte/r für Bäderbetriebe",
                "Beton- und Stahlbetonbauer/in", "Marketingfachkraft/-assistent/in",
                "Kaufmann/-frau im Gesundheitswesen", "Augenoptiker/in",
                "Kaufmännische/r Assistent/in im Bereich Büro/Sekretariat", "Goldschmied/in",
                "Milchtechnologe/-technologin", "Internationale/r Betriebswirt/in", "Orthopädieschuhmacher/in",
                "Kaufmännische/r Assistent/in im Bereich Datenverarbeitung/Rechnungswesen",
                "Pflegefachfrau / Pflegefachmann", "Assistent/in Betriebsleitung im Gartenbau", "Flugbegleiter/in",
                "Informatikkaufmann/-frau", "Trockenbaumonteur/in", "Elektrotechnische/r Assistent/in",
                "Holzmechaniker/in", "Buchbinder/in", "Kaufmann/-frau für Büromanagement",
                "Elektroniker/in für Geräte und Systeme", "Ergotherapeut/in",
                "Kaufmann/-frau für Marketingkommunikation", "Industriemechaniker/in", "Finanzassistent/in",
                "Straßenwärter/in", "Verfahrensmechaniker/in für Beschichtungstechnik",
                "Rechtsanwalts- und Notarfachangestellte/r", "Zahntechniker/in", "Bauzeichner/in",
                "Duales Studium Bank", "Bestattungsfachkraft", "Ausbaumanager/in", "Fotodesigner/in",
                "Technische/r Offiziersassistent/in", "Buchhändler/in", "Tierwirt/in", "Fachberater/in Vertrieb",
                "Parkettleger/in", "Kaufmännische/r Assistent/in für Betriebsinformatik",
                "Duales Studium Wirtschaftsingenieur", "Kaufmann/-frau für Dialogmarketing", "Fluggerätmechaniker/in",
                "Medienkaufmann/-frau Digital und Print", "Altenpflegehelfer/-in", "Podologe/Podologin",
                "Tourismuskaufmann/-frau für Privat- und Geschäftsreisen", "Florist/in", "Pferdewirt/in",
                "Fahrradmonteur/in", "PTA - Pharmazeutisch-technische/r Assistent/in", "Uhrmacher/in",
                "Straßenbauer/in", "Hotelkaufmann/-frau", "Lacklaborant/in", "Chemielaborant/in", "Maurer/in",
                "Wirtschaftsjurist/in – Wirtschaftsrecht (Bachelor of Laws)", "Gesundheits- und Krankenpfleger/in",
                "Landwirt/in", "Maler/in und Lackierer/in", "Fachlagerist/in",
                "Kaufmann/-frau für audiovisuelle Medien", "Polizist/in bei der Landespolizei", "Diätassistent/in",
                "Tiefbaufacharbeiter/in", "Fachmann/-frau für Systemgastronomie", "Fachkraft für Veranstaltungstechnik",
                "Drogist/in", "Gestalter/in für visuelles Marketing", "Nautische/r Offiziersassistent/in",
                "Altenpfleger/in", "Bühnentänzer/in", "Notarfachangestellte/r",
                "Fachangestellte/r für Arbeitsmarktdienstleistungen", "Chemikant/-in",
                "Internationale/r Luftverkehrsassistent/in", "Binnenschiffer/-in", "Film- und Videoeditor/-in",
                "Kosmetiker/in", "Fachkraft für Schutz und Sicherheit", "Fachkraft im Fahrbetrieb",
                "Betriebswirt/in für allgemeine Betriebswirtschaft",
                "Technische/r Assistent/in im Bereich Elektronik und Datentechnik", "Eurokaufmann/-frau",
                "Duales Studium Verwaltungsinformatik", "Gerüstbauer/in", "Investmentfondskaufmann/-frau",
                "Fachkraft im Gastgewerbe", "Handelsassistent/in / Fachwirt/in - Vertrieb im Einzelhandel",
                "Hauswirtschafter/in", "Koch/Köchin", "Duales Studium Gesundheitswesen", "Textil- und Modenäher/in",
                "Glaser/in", "Mediengestalter/in Digital und Print", "Pharmazeutisch-kaufmännische/r Angestellte/r",
                "Feuerungs- und Schornsteinbauer/in", "Chemisch-technische/r Assistent/in", "Rohrleitungsbauer/in",
                "Duales Studium Mathematik", "Mediengestalter/in Bild und Ton",
                "Medizinische/r Fachangestellte/r (MFA)", "Fachkraft für Lebensmitteltechnik",
                "Sozialversicherungsfachangestellte/r", "Physiotherapeut/in", "Servicefachkraft für Dialogmarketing",
                "Modedesigner/in", "Erzieher/in", "Technische/r Assistent/in für Metallografie und Werkstoffkunde",
                "Technische/r Systemplaner/in", "Verwaltungsfachangestellte/r", "Anlagenmechaniker/in",
                "Karosserie- und Fahrzeugbaumechaniker/in", "Fluglotse/-lotsin", "Duales Studium Verwaltung",
                "Rollladen- und Sonnenschutzmechatroniker/in", "Baugeräteführer/in", "Bodenleger/in",
                "Schifffahrtskaufmann/-frau", "Mathematisch-technische/r Assistent/in", "Gleisbauer/in",
                "Industrieelektriker/in", "Werbetechniker/in", "Fachkraft für Metalltechnik"
            };
        }
        
        public static string[,] GetTitel()
        {
            return new[,]
            {
                {"B.A.", "Bachelor of Arts"},
                {"BBA", "Bachelor of Business Administration"},
                {"B.Sc.", "Bachelor of Science"},
                {"LL.B.", "Bachelor of Laws"},
                {"B.Ed.", "Bachelor of Education"},
                {"B.Eng.", "Bachelor of Engineering"},
                {"B.F.A.", "Bachelor of Fine Arts"},
                {"B.Mus.", "Bachelor of Music"},
                {"B.M.A", "Bachelor of Musical Arts"},
                {"M.A.", "Master of Arts"},
                {"M.Sc.", "Master of Science"},
                {"M.Eng.", "Master of Engineering"},
                {"LL.M.", "Master of Laws"},
                {"M.F.A.", "Master of Fine Arts"},
                {"M.Mus.", "Master of Music"},
                {"M.Ed.", "Master of Education"},
                {"M.A.", "Magister Artium"},
                {"M.Sc.", "Magister Scientiarum"},
                {"LL.M.", "Legum Magister"},
                {"MLE", "Magister Legum Europae"},
                {"Mag.rer.publ.", "Magister rerum publicarum"},
                {"Mag.theol. bzw. M.Theol.", "Magister Theologiae"},
                {"Mag.iur.", "Magister iuris"},
                {"M.Th.", "Magister Theologiae"},
                {"Dipl.-Inf. (DH)", "Diplom-Informatiker (Duale Hochschule)"},
                {"Dipl.-Ing. (DH)", "Diplom-Ingenieur (Duale Hochschule)"},
                {"Dipl.-Betriebsw. (DH)", "Diplom-Betriebswirt (Duale Hochschule)"},
                {"Dipl.-Wirtsch.-Inf. (DH)", "Diplom-Wirtschaftsinformatiker (Duale Hochschule)"},
                {"Dipl.-Soz.päd. (DH)", "Diplom-Sozialpädagoge (Duale Hochschule)"},
                {"Dr.agr.(agriculturae)", "Doktor derAgrarwissenschaft"},
                {"Dr.B.A.(D.B.A.)", "Doctor of Business Administration"},
                {"Dr.biol.anim.(biologiae animalis)", "Doktor derTierphysiologie"},
                {"Dr.biol.hom.(biologiae hominis)", "Doktor derHumanbiologie"},
                {"Dr.cult.(culturae)", "Doktor derKulturwissenschaften"},
                {
                    "Dr.disc.pol.(disciplinarum politicarum)",
                    "Doktor derSozialwissenschaftenan derGeorg-August-Universität Göttingen(Politik-undSozialwissenschaften)"
                },
                {
                    "Dr.-Ing.(Doktoringenieur)",
                    "Doktor derIngenieurwissenschaften"
                },
                {
                    "Dr.iur.(iuris)",
                    "Doktor der Rechte bzw. Doktor des Rechts (auch:jur.für „juris“) oder: (iurisprudentiae) Doktor derRechtswissenschaft"
                },
                {
                    "Dr.iur.can.(iuris canonici)",
                    "Doktor derkanonischen Rechtswissenschaften(d.h. des römisch-katholischenKirchenrechts)"
                },
                {"Dr.iur. et rer.pol. (iuris et rerum politicarum)", "Doktor der Rechts- undStaatswissenschaften"},
                {"Dr.math.(mathematicae)", "Doktor derMathematik"},
                {"Dr.med.(medicinae)", "DoktorderMedizin"},
                {"Dr.med.dent.(medicinae dentariae)", "Doktor derZahnheilkunde/Zahnmedizin"},
                {"Dr.med.sci.", "Doktor der Medizinischen Wissenschaft an derTU München"},
                {"Dr.med.vet.(medicinae veterinariae)", "Doktor derTiermedizin"},
                {"Dr.nat.med.", "Doktor der naturwissenschaftlichenMedizin"},
                {"Dr.nat.techn.(naturalium technicarum)", "Doktor derBodenkultur"},
                {"Dr.oec.(oeconomiae)", "Doktor der Wirtschafts- /Verwaltungswissenschaften"},
                {"Dr.oec.publ.(oeconomiae publicae)", "Doktor der Staatswissenschaften / Volkswirtschaft"},
                {"Dr.oec.troph.(oecotrophologiae)", "Doktor der Ernährungswissenschaften /Haushaltswissenschaft"},
                {"Dr.paed.(paedagogiae)", "Doktor derErziehungswissenschaften"},
                {"Dr.pharm.(pharmaciae)", "Doktor derPharmazie"},
                {"Dr.phil.(philosophiae)", "Doktor derPhilosophie"},
                {
                    "Dr.phil. in art.(philosophiae in artibus)",
                    "Doktor der Philosophie in den Künsten (künstlerisch-wissenschaftlich)"
                },
                {
                    "Dr.phil.nat.(philosophiae naturalis)",
                    "Doktor derNaturwissenschafteninFrankfurt am Mainaber anstelle des Dr. rer. nat."
                },
                {"Dr.PH(public health)", "Doktor derPublic Health"},
                {
                    "Dr.rer.agr.(rerum agriculturarum)",
                    "Doktor der Landbauwissenschaften bzw.LandwirtschaftundBodenkultur"
                },
                {"Dr.rer.biol.hum.(rerum biologiae humanae)", "Doktor derHumanbiologie"},
                {"Dr.rer.biol.vet.(rerum biologiae veterinariae)", "Doktor derVeterinärbiologie"},
                {"Dr.rer.cult.(rerum culturarum)", "Doktor derKulturwissenschaften"},
                {"Dr.rer.cur.(rerum curae)", "Doktor derPflegewissenschaften"},
                {"Dr.rer.forest.(rerum forestalium)", "Doktor derForstwissenschaften(auch ohne „rer.“)"},
                {"Dr.rer.hort.(rerum horticulturarum)", "Doktor derGartenbauwissenschaften"},
                {"Dr.rer.hum.(rerum humanarum)", "Doktor der Medizinwissenschaften[25]"},
                {"Dr.rer.med.(rerum medicarum)", "Doktor der Medizinwissenschaften"},
                {
                    "Dr.rer.medic.(rerum medicinalium)",
                    "Doktor der theoretischen Medizin[26][27]/ Medizinwissenschaften[28][29]/Biomedizin/Medizintechnologie/ medizinischenBiometrieundBioinformatik/Gesundheitswissenschaften[30]"
                },
                {"Dr.rer.merc.(rerum mercantilium)", "Doktor derHandelswissenschaften"},
                {"Dr.rer.mont.(rerum montanarum)", "Doktor der Bergbauwissenschaften"},
                {
                    "Dr.rer.nat.(rerum naturalium)", "Doktor derNaturwissenschaften"
                },
                {"Dr.rer.oec.(rerum oeconomicarum)", "Doktor derWirtschaftswissenschaften"},
                {"Dr.rer.physiol.(rerum physiologicarum)", "Doktor derHumanbiologie"},
                {
                    "Dr.rer.pol.(rerum politicarum)", "Sammelbegriff für Doktoren derPolitikwissenschaft"
                },
                {"Dr.rer.publ.(rerum publicarum)", "Doktor derVerwaltungswissenschaften"},
                {"Dr.rer.sec.(rerum securitatis)", "Doktor derSicherheitswissenschaften"},
                {"Dr.rer.silv.(rerum silvestrium bzw. rerum silvaticarum[31])", "Doktor derForstwissenschaften"},
                {"Dr.rer.soc.(rerum socialium)", "Doktor derSozialwissenschaften"},
                {"Dr.rer.tech.(rerum technicarium)", "Doktor derTechnischen Wissenschaften"},
                {"Dr.sc.agr.(scientiarum agrarium)", "Doktor der Agrarwissenschaften"},
                {"Dr.sc.hum.(scientiarum humanarum)", "Doktor der Humanwissenschaften"},
                {"Dr.sc.mus.(scientiae musicae)", "Doktor der Musikwissenschaften"},
                {"Dr.sc.oec.(scientiarum oeconomicarum)", "Doktor der Wirtschaftswissenschaften"},
                {"Dr.sc.phil.(scientiarum philosophiae)", "Doktor der Philosophiewissenschaften"},
                {"Dr.sc.pol.(scientiarum politicarum)", "Doktor der Wirtschafts- und Sozialwissenschaften"},
                {"Dr.sc.soc.(scientiae socialis)", "Doktor derSozialwissenschaften"},
                {"Dr.sc.techn.(scientiarum technicarum)", "Doktor der technischen Wissenschaften"},
                {"Dr.Sportwiss.", "Doktor derSportwissenschaften"},
                {"Dr.theol.(theologiae)", "Doktor derTheologie"},
                {"Dr.troph.(trophologiae)", "Doktor derErnährungswissenschaft"}
            };
        }

        public static string[] GetDokumentArtList()
        {
            return new[]
            {
                "Gewerbeanmeldung",
                "Ausweiskopie",
                "34D-Nachweis",
                "Zustimmung zur Erteilung der Schufa-Auskunft",
                "Vertrag",
                "Persönliche Daten"
            };
        }
    }
}